version: "3"

services:
  mysql:
    image: "mysql/mysql-server:8.0"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    restart: always
